Enable typescript
stjude/proteinpaint pull request #192
Opened 2023-05-23 15:30 UTC by creilly8

2023-05-23 15:59 UTC, siosonel requested changes
@creilly8 I think we should enable typescript only for server side for now, so no need to have client-side code changes in this PR branch? Not sure how close @aacic is with the disco plot changes, but I would assume he would activate typescript for client-side when his branch is ready.

Also, I think there also has to be a typescript devDependency in server/package.json.

Lastly, I'd prefer not committing the empty line additions in server/src/app.js.

2023-05-23 16:17 UTC, creilly8 commented
Thanks @siosonel. Those changes are made.

2023-05-23 17:13 UTC, siosonel submitted a review, later dismissed
Thanks, works

2023-05-25 22:16 UTC, siosonel approved these changes

2023-05-25 22:16 UTC, merged